
version: "3.8"
services:
  redis:
    image: redis 
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8001:8000'   # API uygulamasının portunu 8001'e değiştir
    command: poetry run uvicorn ocr_analysis.main:app --host 0.0.0.0 --port 8000